CREATE TABLE city_day_event_counts_plus (
  num_conflicts BIGINT,
  sum_num_mentions BIGINT,
  sum_num_articles BIGINT,
  sum_num_sources BIGINT,
  actiongeo_lat DOUBLE,
  actiongeo_long DOUBLE,
  sqldate BIGINT,
  geonameid text,
  name text,
  asciiname text,
  alternatenames text,
  latitude DOUBLE,
  longitude DOUBLE,
  feature_class text,
  feature_code text,
  country_code text,
  cc2 text,
  admin1_code text,
  admin2_code text,
  admin3_code text,
  admin4_code text,
  population text,
  elevation_meters BIGINT,
  dem text,
  timezone text,
  modification text
);
