CREATE TABLE `events` (
  `row_names` text,
  `GLOBALEVENTID` bigint(20) DEFAULT NULL,
  `SQLDATE` bigint(20) DEFAULT NULL,
  `MonthYear` bigint(20) DEFAULT NULL,
  `Year` bigint(20) DEFAULT NULL,
  `FractionDate` double DEFAULT NULL,
  `Actor1Code` varchar(3),
  `Actor1Name` text,
  `Actor1CountryCode` varchar(4),
  `Actor1KnownGroupCode` varchar(4),
  `Actor1EthnicCode` varchar(4),
  `Actor1Religion1Code` varchar(4),
  `Actor1Religion2Code` varchar(4),
  `Actor1Type1Code` varchar(4),
  `Actor1Type2Code` varchar(4),
  `Actor1Type3Code` varchar(4),
  `Actor2Code` varchar(4),
  `Actor2Name` text,
  `Actor2CountryCode` varchar(4),
  `Actor2KnownGroupCode` varchar(4),
  `Actor2EthnicCode` varchar(4),
  `Actor2Religion1Code` varchar(4),
  `Actor2Religion2Code` varchar(4),
  `Actor2Type1Code` varchar(4),
  `Actor2Type2Code` varchar(4),
  `Actor2Type3Code` varchar(4),
  `IsRootEvent` bigint(20) DEFAULT NULL,
  `EventCode` bigint(20) DEFAULT NULL,
  `EventBaseCode` bigint(20) DEFAULT NULL,
  `EventRootCode` bigint(20) DEFAULT NULL,
  `QuadClass` bigint(20) DEFAULT NULL,
  `GoldsteinScale` double DEFAULT NULL,
  `NumMentions` bigint(20) DEFAULT NULL,
  `NumSources` bigint(20) DEFAULT NULL,
  `NumArticles` bigint(20) DEFAULT NULL,
  `AvgTone` double DEFAULT NULL,
  `Actor1Geo_Type` bigint(20) DEFAULT NULL,
  `Actor1Geo_FullName` text,
  `Actor1Geo_CountryCode` varchar(4),
  `Actor1Geo_ADM1Code` varchar(4),
  `Actor1Geo_Lat` double DEFAULT NULL,
  `Actor1Geo_Long` double DEFAULT NULL,
  `Actor1Geo_FeatureID` text,
  `Actor2Geo_Type` bigint(20) DEFAULT NULL,
  `Actor2Geo_FullName` text,
  `Actor2Geo_CountryCode` varchar(4),
  `Actor2Geo_ADM1Code` varchar(4),
  `Actor2Geo_Lat` double DEFAULT NULL,
  `Actor2Geo_Long` double DEFAULT NULL,
  `Actor2Geo_FeatureID` text,
  `ActionGeo_Type` bigint(20) DEFAULT NULL,
  `ActionGeo_FullName` text,
  `ActionGeo_CountryCode` varchar(4),
  `ActionGeo_ADM1Code` varchar(4),
  `ActionGeo_Lat` double DEFAULT NULL,
  `ActionGeo_Long` double DEFAULT NULL,
  `ActionGeo_FeatureID` text,
  `DATEADDED` datetime, -- bigint(20) DEFAULT NULL,
  `SOURCEURL` text
)
