---
title: "Conflict Analysis R Scripts 5"
subtitle: 'Regression and Results'
author: "Aimee Barciauskas, Harihara Subramanyam, Roger Cuscó"
date: "November 28, 2015"
output: pdf_document
---

# Master Table

$log_num_conflicts = lag.log_num_mentions + same_region_avg + other_region_avgs + log_population + log_population_sq + wday$

```{r}
data <- cbind(data, with(data, model.matrix(~ wday + 0)))
city_data <- data[,c('city_mean','city','latitude','log_population','longitude','log_population_sq','geonameid')]
city_data <- merge(city_data, cities[,c('city','regions')], by = 'city')
city_data <- unique(city_data)
city_data$isWashingtonDC <- ifelse(city_data$city == 'Washington, D.C., DC', 1, 0)

data2 <- data[,c('log_num_conflicts', 'city', 'datef','wdayweekend')]
data2 <- dcast(data = data2, formula = datef ~ city, value.var = 'log_num_conflicts', fun.aggregate = sum)
data2 <- melt(data2, id.vars='datef')
data2 <- slide(data2, Var = "value", GroupVar = "variable", slideBy = -1)

weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')

data2$wday <- factor((weekdays(data2$datef) %in% weekdays1), 
         levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))
data2 <- cbind(data2, with(data2, model.matrix(~ wday + 0)))

#install.packages('DataCombine')
library(DataCombine)
colnames(data2) <- c('datef','city','log_num_conflicts','lag.log_num_conflicts','wday','weekend','weekday')

data3 <- merge(data2, final, by=c('city','datef'))

master.table <- merge(data3, city_data, by='city')
#head(master.table <- unique(master.table)


master.table.2 <- master.table[,c('log_num_conflicts','lag.log_num_conflicts','same_region', 'region.1', 'region.2', 'region.3', 'region.4', 'region.5','log_population','log_population_sq', 'isWashingtonDC','weekend')]
master.table.2[is.na(master.table.2)] <- 0
#head(master.table.2)
m1 <- lm(data = master.table.2, log_num_conflicts ~ 0 + .)

master.table.2 <- master.table[,c('log_num_conflicts','lag.log_num_conflicts','log_population_sq', 'isWashingtonDC','weekend')]
master.table.2[is.na(master.table.2)] <- 0
#head(master.table.2)
m2 <- lm(data = master.table.2, log_num_conflicts ~ 0 + .)
summary(m2)
#install.packages('stargazer')
library(stargazer)
capture.output(stargazer(m1, m2, align=TRUE, type = 'html', omit.stat=c("f")), file = 'summary.html')
```

Cross - validation

```{r, echo=FALSE, warnings=FALSE, messages=FALSE}
# cross - validate using 5 subsets of the master table

ridge.reg <- function(y, X, lambda) {
  # here we compute the coefficients for the ridge regression using the 
  # parameter lambda inputed as third element in the function call. 
  beta_ridge = solve(t(X)%*%X + diag(lambda, ncol(X)))%*%t(X)%*%y
  beta_ridge
}

B <- 5
blocks <- ceiling( B * (1:nrow(master.table.2)/nrow(master.table.2)))

models = list()
r_squareds = c()
adj_r_squareds = c()
MSEs = c()
cond = c()

lambda = 0

for (i in 1:B) {
  
  train = master.table.2[ blocks != i, ]
  test = master.table.2[ blocks == i, ]
  
  # models[[i]] = lm(data = train, log_num_conflicts ~ 0 + .)
  beta = ridge.reg(as.matrix(train[,1]), as.matrix(train[,-1]), lambda)
  # prediction = predict(models[[i]], newdata = test)
  prediction = as.matrix(test[,-1]) %*% beta
  residuals = ( prediction - test$log_num_conflicts)
  
  degrees_freedom = (nrow(test) - 1)/(nrow(test) - (ncol(test)-1) - 1)
  RSS = sum(residuals^2)
  TSS = sum((mean(test$log_num_conflicts) - test$log_num_conflicts )^2)
  r_squareds[i] = 1 - (RSS/TSS)
  adj_r_squareds[i] = 1 - ( 1 - r_squareds[i])*degrees_freedom
  MSEs[i] = mean(residuals^2)
  
  XX = ( as.matrix(t(train[,-1])) %*% as.matrix(train[,-1]) ) + diag(lambda, ncol(as.matrix(train[,-1])))
  cond[i] = max(eigen(XX)$values) / min(eigen(XX)$values)
}

r_squareds
adj_r_squareds
MSEs
mrsqs <- mean(r_squareds)
marsqs <- mean(adj_r_squareds)
mmse <- mean(MSEs)
cond
mat <- matrix(c(r_squareds, mrsqs, MSEs, mmse,adj_r_squareds, marsqs), ncol=5, nrow=3, byrow = TRUE)
colnames <- c(unlist(lapply('Test ', paste0, 1:4)), 'Average')
rownames <- c('R-squared', 'Adjusted R-Squared', 'Mean Squared Error')
dimnames(mat) <- list(rownames, colnames)
library(xtable)
mat.table <- xtable(mat)
capture.output(print(mat.table, type = 'html'), file = 'cross-val.html')
```