---
title: "Conflict Analysis Project - VAR analysis"
author: "Aimee Barciauskas"
date: "November 23, 2015"
output: pdf_document
---



```{r}
library(RMySQL)
library(reshape)

# MySQL [gdelt]> create table count_city_event_days as select feature_id,count(*) as days_count from city_day_event_counts group by feature_id;
# create table top_cities as select * from count_city_event_days order by days_count desc limit 100;
# create table top_cities_with_events as select * from top_cities left join city_day_event_counts on top_cities.feature_id = city_day_event_counts.feature_id;
#
con <- dbConnect(RMySQL::MySQL(), user="root", password="root", dbname = "gdelt")

res <- dbSendQuery(con, "select * from top_cities_with_events where sqldate > 20130331")

# n = -1 fetches all results, instead of default limit of first 500
data <- dbFetch(res, n = -1)

# epsilon <- a matrix of c cities and n days
dates_and_featureids <- data[,c('num_conflicts','sqldate','feature_id')]

# head(data_subset)
events_by_date_city <- cast(data = dates_and_featureids, formula = sqldate ~ feature_id, value = 'num_conflicts')
events_by_date_city[is.na(events_by_date_city)] <- 0
# Reverse order to make the VAR equation work
events_by_date_city <- apply(events_by_date_city, 2, rev)

# p: number of days to regress upon
# epsilon.t: matrix of dependent variables (events_by_date_and_city minus p + 1 days from start)
# epsilon.tp: matrix of explanatory variables (events_by_date_and_city minus first day minus p days from start)
p <- 2 # start easy
total_days <- nrow(events_by_date_city)
epsilon.t <- events_by_date_city[1:(total_days - (p+1)),]
epsilon.tp <- events_by_date_city[2:(total_days - p),]

# estimate a model for the first column of epsilon on the first column of tp
# Regress on 2 days
epsilon.t.1 <- embed(c(NA,NA,epsilon.t[,1]), 3)
data_to_regress <- data.frame(epsilon.t.1[3:nrow(epsilon.t.1),])

model.1 <- lm(X1 ~ ., data = data_to_regress)
summary(model.1)

library(vars)
vars.model <- VAR(epsilon.t[,1:2], p = 2)
coef(vars.model)
```

## Space Exploration

```{r}
library(reshape)
library(Imap)
head(data)

feature_ids <- unique(data$feature_id)


# first city
dates <- unique(data$sqldate)
dates <- as.matrix(dates)
colnames(dates) <- c('sqldate')
city <- subset(data, feature_id == 1066650)
city <- merge(dates, city, by = 'sqldate', all.x = TRUE)
rownames(city) <- dates
city[is.na(city)] <- 0

other_cities <- subset(data, feature_id != 1066650)

other_city_names <- unique(other_cities$feature_id)

city_matrix <- matrix(0, nrow = nrow(city), ncol = 1+ length(other_city_names))
city_matrix[,1] <- city[,c('num_conflicts')]
rownames(city_matrix) <- dates
colnames(city_matrix) <- c(1066650, other_city_names)
head(city_matrix)

# Add the distance
for (idx in 1:nrow(other_cities)) {
  second_city <- other_cities[idx,]
  sqldate <- second_city['sqldate']
  num_conflicts <- second_city['num_conflicts']

  # gdist(lon.1, lat.1, lon.2, lat.2
  dist_from_city <- gdist(
    city[1,'prim_long_dec'],
    city[1,'prim_lat_dec'],
    as.numeric(second_city['prim_long_dec']),
    as.numeric(second_city['prim_lat_dec']),
    units = 'miles')

  city_matrix[as.character(sqldate), as.character(second_city['feature_id'])] <- as.numeric(num_conflicts)*dist_from_city
}

# THIS IS ALL WRONG ~ need a matrix that is repeated values for the dependent var for it's interaction with all cities (although thi implies y's are same-valued...)
# [y_{days_rep},...yt1,y12,...,ytk] ~ [X_{city,day} x c(distance,num_conflicts)]
#
city_matrix <- data.frame(city_matrix)
head(city_matrix)
model.1 <- lm(X1066650 ~ ., data = city_matrix)
summary(model.1)
```
