---
title: "VAR analysis"
author: "Aimee Barciauskas"
date: "November 26, 2015"
output: html_document
---

```{r}
library(RMySQL)
library(reshape)
library(ggplot2)

con <- dbConnect(RMySQL::MySQL(), user="root", password="root", dbname = "gdelt")

res <- dbSendQuery(con, "select * from top_cities where sqldate > 20130331")
data <- dbFetch(res, n = -1)

# Standard data formatting
data$datef <- as.Date(as.character(data$sqldate), format = '%Y%m%d')
data$city <- paste0(data$name, ', ', data$admin1_code)
```

## Removing Washington, D.C. (for now)

```{r}
data <- subset(data, geonameid != '4140963')
```

## De-trendify (using differences)

```{r}
# each num_mentions should be num_mentions - mean, sd for same day
day_means <- tapply(data$num_conflicts, data$sqldate, FUN=mean)
day_means <- cbind(as.matrix(day_means), as.numeric(row.names(day_means)))
colnames(day_means) <- c('date_mean','sqldate')

data <- merge(data, day_means, by = 'sqldate', all.x = TRUE)

data$std_num_conflicts <- (data$num_conflicts - data$date_mean)

# Sanity check
# d2 <- subset(data, sqldate == 20150101)
# sum(d2$std_num_conflicts)
plot(log(sample(data$std_num_conflicts, 10000)))
```

From the below it does look like there is relative growth and decline

```{r}
library(dplyr)
random_cities <- sample(unique(data$city), 20)
random_sample <- subset(data, city %in% random_cities)

ggplot(data = random_sample,
       aes(x = datef, y = std_num_conflicts, color = city)) +       
  geom_line(aes(group = city))

ggplot(data = random_sample,
       aes(x = datef, y = std_num_conflicts, color = city)) +       
  stat_smooth(aes(group = city), method = 'lm')
```

# VAR

Create network matrix

```{r}
library(reshape2)
date_by_city_matrix <- data[,c('std_num_conflicts','datef','city')]

# fun aggregate needed as some cells are not represented -> 0
events_by_date_city <- dcast(data = date_by_city_matrix, formula = datef ~ city, value.var = 'std_num_conflicts', fun.aggregate = sum)

# Sanity check
# head(events_by_date_city[,'Tulsa, OK'], n = 20)
# head(data[data$city == 'Tulsa, OK',][,c('std_num_conflicts','datef')], n = 10)

# Make date column rownames
rownames(events_by_date_city) <- events_by_date_city$datef
events_by_date_city <- events_by_date_city[,setdiff(colnames(events_by_date_city), 'datef')]

X <- events_by_date_city
my.cov <- function(X) {
  n <- nrow(X)
  d <- data.frame(mean = colMeans(X))
  means <- t(do.call("cbind", replicate(n, d, simplify = FALSE)))
  diff_matrix <- as.matrix(X - means)
  1/(n-1) * t(diff_matrix) %*% diff_matrix
}

my.cor <- function(cov.matrix) {
  # expect a square matrix
  cor.matrix <- matrix(0, nrow = nrow(cov.matrix), ncol = nrow(cov.matrix))
  for (i in 1:ncol(cov.matrix)) {
    for (j in 1:nrow(cov.matrix)) {
      cor.matrix[i,j] <- cov.matrix[i,j]/(sqrt(cov.matrix[i,i])*sqrt(cov.matrix[j,j]))
    }
  }
  cor.matrix
}
# my.cov(X)[1:3,1:3]
# cov(X)[1:3,1:3]

# my.cor(cov(X))[1:3,1:3]
# cor(X)[1:3,1:3]
```

Calculate partial correlation

```{r}
pij <- 18.55161/(sqrt(57.91767)*sqrt(51.61613))

model1 <- lm(`Boston, MA` ~ 0 + ., data = X)
summary(model1)
```

Partial Correlation

* `correlation:` rho_ij
* `effect:` theta_ij

```{r}
K <- solve(my.cov(X))
i <- 1
j <- 2
(rho_ij <- -K[i,j]/sqrt(K[i,i]*K[j,j]))
(theta_ij <- rho_ij * sqrt(K[i,j]/K[j,j]))
# QUESTION: Why are these different?
(theta_ij <- -K[i,j]/K[i,i])
```

Simple Lasso

```{r}
source('/Users/aimeebarciauskas/Box Sync/abarciausksas/myfiles/conflicts_analysis_project/scripts/data_expoloration/lasso.R')
# concentration matrix

# i <- 1
# j <- 2
# for one matrix
y <- as.numeric(X[,1])
x <- as.matrix(X[,2:ncol(X)])
beta.hat <- lasso.reg(y, x, 2000)
beta.hat
```

Space

1) Take kiihat 
```
```

